### PR TITLE
improvement/anchors

### PR DESCRIPTION
**Pull request by oozoofrog**
- modifying some functions in Anchors to more clearer overloading for autocompletion instead of using default parameter values.
- add tests for anchor rules

### CODE REVIEW

**Comment by oozoofrog** [comment]
@gmlwhdtjd 
how about think that versioning to 1.3.5 until this pr.

**Review by gmlwhdtjd — APPROVED** [review]

**Comment by gmlwhdtjd** [comment]
I think it's better because it's much cleaner than using default parameters! 👍

**Comment by gmlwhdtjd** [comment]
> @gmlwhdtjd
> how about versioning to 1.3.5 after merged this

I think 1.4.0 is better than 1.3.5 cuz Achors's API is changed

**Comment by oozoofrog** [comment]
> > @gmlwhdtjd
> > how about versioning to 1.3.5 after merged this
> 
> I think 1.4.0 is better than 1.3.5 cuz Achors's API is changed

you right!

**Pull request merged**
