### PR TITLE
add default configurable properties for UISwitch

### PR DESCRIPTION
**Pull request by oozoofrog**

### CODE REVIEW

**Review by gmlwhdtjd — COMMENTED** [review]
I think some properties are missing like thumbTintColor, onTintColor
Check it please

**Comment by oozoofrog** [comment]
> I think some properties are missing like thumbTintColor, onTintColor
> Check it please

update properties for remains

**Review by gmlwhdtjd — APPROVED** [review]
GOOOOD👍

**Comment by oozoofrog** [comment]
> GOOOOD👍

THANXXX 👍

**Pull request merged**
