### PR TITLE
Layout.anchors now can added to its sublayouts[ViewLayout]

### PR DESCRIPTION
**Pull request by oozoofrog**

### CODE REVIEW

**Review by gmlwhdtjd — CHANGES_REQUESTED** [review]
```swift
root {
    GroupLayout {    // GroupLayout is a layout so it will work with new features
        red
        blue
    }.anchors {
        Anchors.size()
    }
}.finalActive()
```
vs
```swift
root {
    group {    // group is a view property, in this case how it work?
        red
        blue
    }.anchors {
        Anchors.size()
    }
}.finalActive()
```

I think this syntax is easy to misunderstand.

And this feature is for GroupLayout.
However, there are changes in the Layout protocol to implement this feature. 
I think this is not a very good implementation direction.

**Comment by oozoofrog** [comment]
> ```swift
> ```swift
> root {
>     GroupLayout {    // GroupLayout is a layout so it will work with new features
>         red
>         blue
>     }.anchors {
>         Anchors.size()
>     }
> }.finalActive()
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> vs
> ```swift
> root {
>     group {    // group is a view property, in this case how it work?
>         red
>         blue
>     }.anchors {
>         Anchors.size()
>     }
> }.finalActive()
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> I think this syntax is easy to misunderstand.
> And this feature is for GroupLayout.
> However, there are changes in the Layout protocol to implement this feature.
> I think this is not a very good implementation direction.
> ```

yeah good good 💯

**Comment by oozoofrog** [comment]
> ```swift
> ```swift
> root {
>     GroupLayout {    // GroupLayout is a layout so it will work with new features
>         red
>         blue
>     }.anchors {
>         Anchors.size()
>     }
> }.finalActive()
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> vs
> ```swift
> root {
>     group {    // group is a view property, in this case how it work?
>         red
>         blue
>     }.anchors {
>         Anchors.size()
>     }
> }.finalActive()
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> I think this syntax is easy to misunderstand.
> And this feature is for GroupLayout.
> However, there are changes in the Layout protocol to implement this feature.
> I think this is not a very good implementation direction.
> ```

sorry I can't understand why you misleading GroupLayout and group view property.

> ```swift
> ```swift
> root {
>     GroupLayout {    // GroupLayout is a layout so it will work with new features
>         red
>         blue
>     }.anchors {
>         Anchors.size()
>     }
> }.finalActive()
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> vs
> ```swift
> root {
>     group {    // group is a view property, in this case how it work?
>         red
>         blue
>     }.anchors {
>         Anchors.size()
>     }
> }.finalActive()
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> I think this syntax is easy to misunderstand.
> And this feature is for GroupLayout.
> However, there are changes in the Layout protocol to implement this feature.
> I think this is not a very good implementation direction.
> ```

**Comment by oozoofrog** [comment]
> ```swift
> ```swift
> root {
>     GroupLayout {    // GroupLayout is a layout so it will work with new features
>         red
>         blue
>     }.anchors {
>         Anchors.size()
>     }
> }.finalActive()
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> vs
> ```swift
> root {
>     group {    // group is a view property, in this case how it work?
>         red
>         blue
>     }.anchors {
>         Anchors.size()
>     }
> }.finalActive()
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> I think this syntax is easy to misunderstand.
> And this feature is for GroupLayout.
> However, there are changes in the Layout protocol to implement this feature.
> I think this is not a very good implementation direction.
> ```

oh, I understand. you point is user can misunderstand diff of anchors in view and layout. am i right?
so, how about renaming like this for clearness?

```swift
root {
  red
  blue
}.anchorsForLayouts {
  Anchors.size()
}
```

**Comment by gmlwhdtjd** [comment]
@oozoofrog 

```swift
root {
    GroupLayout {    // GroupLayout is a layout so it will work with new features
        red
        blue
    }.anchors {
        Anchors.size()
    }
}.finalActive()
```
In this case, by new feature, `Anchors.size()` will apply to `red` and `blue`

```swift
root {
    group {    // group is a view property, in this case how it work?
        red
        blue
    }.anchors {
        Anchors.size()
    }
}.finalActive()
```
On the other hand, in this case `Anchors.size()` will be applied to the `group`.
The user may have expected `Anchors.size()` to be applied to `red` and `blue` like in the case above.

The difference between the two syntaxes is just whether it is a GroupLayout or a group.

And, not recommended, but what if you have a view property called `GroupLayout`?

**Pull request closed without merging**
