### PR TITLE
SwiftLayoutPrinter

### PR DESCRIPTION
**Pull request by oozoofrog**
- label properties
- print config properties
- print config
- update config test
- print quotation mark on identifying
- print identifier improving

### CODE REVIEW

**Comment by oozoofrog** [comment]
```swift
root {
    UILabel().identifying("\(capIdentifier)").config {
        $0.font = UIFont.systemFont(ofSize: 12.0)
        $0.lineBreakMode = .byTruncatingHead
        $0.numberOfLines = 0
        $0.text = "HELLO"
        $0.textAlignment = .center
    }.anchors {
        Anchors(.top, .leading, .trailing)
    }
    UILabel().identifying("\(shoeIdentifier)").config {
        $0.font = UIFont.systemFont(ofSize: 17.0)
    }.anchors {
        Anchors(.top).equalTo("\(capIdentifier)", attribute: .bottom)
        Anchors(.bottom, .leading, .trailing)
    }
}
```

**Comment by gmlwhdtjd** [comment]
> @gmlwhdtjd supporting some properties of label in currently.

I'm very surprised that the feature could be realized.
If this feature is completed, it will be a really useful feature!! 👍

**Comment by gmlwhdtjd** [comment]
As more features are added to `SwiftLayoutPrinter`, it is recommended to split the file.

**Comment by oozoofrog** [comment]
I missed test of macOS

**Comment by oozoofrog** [comment]
> As more features are added to `SwiftLayoutPrinter`, it is recommended to split the file.
> Or
> If you want to hide parts that only used in `SwiftLayoutPrinter` from other parts of the package
> It is recommended to create a target called "SwiftLayoutPrinter".

time come.

**Comment by oozoofrog** [comment]
@gmlwhdtjd I decide reinvent SwiftLayoutPrinter, except interface.

**Comment by oozoofrog** [comment]
@gmlwhdtjd give up this by massive conflicts. anyway I should do reinvent SwiftLayoutPrinter

**Pull request closed without merging**
