### PR TITLE
add updateIdentifiers method

### PR DESCRIPTION
**Pull request by gmlwhdtjd**
- deprecate LayoutOptions.automaticIdentifierAssignment
- add Layout.updateIdentifiers(rootObject:) to provide deprecated features

### CODE REVIEW

**Review by oozoofrog — APPROVED** [review]
👍 👍 💯 
elastic refactoring.

**Comment by oozoofrog** [comment]
I start thinking by this pr, LayoutOptions can be disappear.

**Comment by gmlwhdtjd** [comment]
> I start thinking by this pr, LayoutOptions can be disappear.

Is there any possibility that other options will be added in the future?
If the possibility is low, it would be good to delete it, but if not, I think we will have duplicate work.

**Comment by oozoofrog** [comment]
> > I start thinking by this pr, LayoutOptions can be disappear.
> 
> Is there any possibility that other options will be added in the future? If the possibility is low, it would be good to delete it, but if not, I think we will have duplicate work.

possibility always exist, but this LayoutOptions was too naive approach of me. update layout is not so core api, it just helper utility procedure in LayoutBuilding(starting don't like this struct too haha). so may be we can create another enum or options set etc, but should not like this.

**Comment by gmlwhdtjd** [comment]
@oozoofrog 
I understand what you are saying and I agree with you. 👍

**Pull request merged**
