### PR TITLE
options

### PR DESCRIPTION
**Pull request by oozoofrog**
- add options
- make accessibility identifier automatically from root object or **LayoutBuilding**

### CODE REVIEW

**Review by gmlwhdtjd — COMMENTED** [review]
I think separating option value and function in LayoutOptions will help when more options are added in the future

**Comment by gmlwhdtjd** [comment]
LayoutOptions.accessibilityIdentifiers seems to be an option that automatically sets view.accessibilityIdentifier to the name of the property where the view is stored, is that correct?

**Comment by oozoofrog** [comment]
> LayoutOptions.accessibilityIdentifiers seems to be an option that automatically sets view.accessibilityIdentifier to the name of the property where the view is stored, is that correct?

yeah, that's correct.

**Comment by oozoofrog** [comment]
> I think separating option value and function in LayoutOptions will help when more options are added in the future

that's reasonable point. ok, D&C.

**Comment by oozoofrog** [comment]
> LayoutOptions.accessibilityIdentifiers seems to be an option that automatically sets view.accessibilityIdentifier to the name of the property where the view is stored, is that correct?

how about like this? 

```swift
Deactivable.updateLayout(OptionParams(options: LayoutOption..., rootObjectForAccessibilityIdentifier: <object>)
```

ooooh... naming... ooo

@gmlwhdtjd

**Comment by gmlwhdtjd** [comment]
> > LayoutOptions.accessibilityIdentifiers seems to be an option that automatically sets view.accessibilityIdentifier to the name of the property where the view is stored, is that correct?
> 
> how about like this?
> 
> ```swift
> Deactivable.updateLayout(OptionParams(options: LayoutOption..., rootObjectForAccessibilityIdentifier: <object>)
> ```
> 
> ooooh... naming... ooo
> 
> @gmlwhdtjd

Is there any reason to get the root object from the user?
Looking at the commits so far, the root detection logic doesn't seem to have much of a problem.

**Comment by oozoofrog** [comment]
> > > LayoutOptions.accessibilityIdentifiers seems to be an option that automatically sets view.accessibilityIdentifier to the name of the property where the view is stored, is that correct?
> > 
> > 
> > how about like this?
> > ```swift
> > Deactivable.updateLayout(OptionParams(options: LayoutOption..., rootObjectForAccessibilityIdentifier: <object>)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ooooh... naming... ooo
> > @gmlwhdtjd
> 
> Is there any reason to get the root object from the user? Looking at the commits so far, the root detection logic doesn't seem to have much of a problem.

there are one reason. because root view and container of views may not same. @gmlwhdtjd

**Comment by gmlwhdtjd** [comment]
@oozoofrog 
Oh! I understood, Then it is a necessary situation.
I wonder if there is a nicer way
Because it's good to give an option as an argument but I think it would be inconvenient to use it to have to create a separate instance again for giving an option.

**Comment by oozoofrog** [comment]
> @oozoofrog
> Oh! I understood, Then it is a necessary situation.
> I wonder if there is a nicer way
> Because it's good to give an option as an argument but I think it would be inconvenient to use it to have to create a separate instance again for giving an option.

agreed. should be more nicer way be somwhere in cells of brain. hey where are you.

**Comment by oozoofrog** [comment]
> @oozoofrog
> Oh! I understood, Then it is a necessary situation.
> I wonder if there is a nicer way
> Because it's good to give an option as an argument but I think it would be inconvenient to use it to have to create a separate instance again for giving an option.

oh may be answer is object itself.

**Comment by oozoofrog** [comment]
> > @oozoofrog
> > Oh! I understood, Then it is a necessary situation.
> > I wonder if there is a nicer way
> > Because it's good to give an option as an argument but I think it would be inconvenient to use it to have to create a separate instance again for giving an option.
> 
> oh may be answer is object itself.

oh may be responder chain is the answer.

**Comment by oozoofrog** [comment]
@gmlwhdtjd ah, i forgot **LayoutBuilding**! its the answer!

**Comment by oozoofrog** [comment]
@gmlwhdtjd new commit come

**Review by gmlwhdtjd — APPROVED** [review]
LGTM👍
It's already great now, BTW it would be even better if there was a way to notify users when using that option without building or when the root view cannot be found!

**Comment by oozoofrog** [comment]
> LGTM👍
> It's already great now, BTW it would be even better if there was a way to notify users when using that option without building or when the root view cannot be found!

thank you. we can figure more better methods eventually.

**Pull request merged**
