### PR TITLE
hiding of Activation class from external of library

### PR DESCRIPTION
**Pull request by oozoofrog**
i can't find now elegant strategy more than using [associated object] for hide activation type from out of library :(

Activations must be released as well when the owner is freed from memory because it has reference of view and constraints for some api features. that means owner must have owning reference of activation type.

so I have two option, using associated object api or user should write activation property like in previous commits.

anyway there are very good advantages to hiding activation property. that give to LayoutBuilding api more usability and flexibility.

please see [LayoutHostingViewController](https://github.com/ioskrew/SwiftLayout/blob/c22d40da2c992c6f94cae343128c6b983dfdddba/Sample/SwiftLayoutSample/SwiftLayoutSample/ViewController.swift#L68)

### CODE REVIEW

**Comment by oozoofrog** [comment]
ok maybe i can floats some ideas

**Review by gmlwhdtjd — APPROVED** [review]
Good idea! 👍
But I think using `AssociatedObject`  is a weakpoint of this implementation

I approve it because this implementation seems to be the best way for now, but it seems necessary to continue to find a more secure implementation method.

**Comment by oozoofrog** [comment]
> Good idea! 👍 But I think using `AssociatedObject` is a weakpoint of this implementation
> 
> I approve it because this implementation seems to be the best way for now, but it seems necessary to continue to find a more secure implementation method.

very agree that point of weakpoint. it need better methods.

**Comment by gmlwhdtjd** [comment]
How about creating a Deactivatable protocol and only opening this part?

If you open only the Deactivatable protocol, I'm worried about how to change the layout or get an animation point later.

**Comment by oozoofrog** [comment]
> How about creating a Deactivatable protocol and only opening this part?
> 
> If we open only the Deactivatable protocol, I'm worried about how to change the layout or get an animation point later.

I see.  case of not using LayoutBuilding should be needs Deactivation or Deactivatable.

**Comment by oozoofrog** [comment]
> How about creating a Deactivatable protocol and only opening this part?
> 
> If we open only the Deactivatable protocol, I'm worried about how to change the layout or get an animation point later.

I see, that need to be case of not using LayoutBuilding.

**Pull request merged**
