### PR TITLE
refactorings and adds

### PR DESCRIPTION
**Pull request by oozoofrog**
*1 pr like 2n pr*

- add LayoutProperty property wrapper
- binding with LayoutProperty to updateLayout

https://user-images.githubusercontent.com/3011832/156927820-e734f23e-4f28-4f59-949e-8f4f7cf84cb0.mov

- LayoutBuilding change to Layoutable
 - Layout to make seems like View protocol and removing LayoutBuilding was my first plan, but, gave up. couldn't find advantage except looks good.
- update SwiftUI representable

스크린샷 2022-03-06 오후 11 14 54

### CODE REVIEW

**Comment by gmlwhdtjd** [comment]
The features you suggested are very attractive and I would like to see them included in our project.
However, there is a risk of the Strong Reference Cycle occurring in the part that has AnyCancellable in Activation, and I think it is also necessary to improve the fact that the user always needs to call initLayout().

So I proposal to implement LayoutProperty by "[Referencing the enclosing 'self' in a wrapper type](https://github.com/apple/swift-evolution/blob/master/proposals/0258-property-wrappers.md#referencing-the-enclosing-self-in-a-wrapper-type)" introduced as a feature of Property Wrappers

This function was also proposed when LayoutProperty was proposed, but it is not yet officially provided.
However, it is judged that all necessary feature have already been satisfied, so we suggest the use of those feature.

I referred to the following site for implementation.
[https://www.swiftbysundell.com/articles/accessing-a-swift-property-wrappers-enclosing-instance/](https://www.swiftbysundell.com/articles/accessing-a-swift-property-wrappers-enclosing-instance/)

**Comment by oozoofrog** [comment]
> The features you suggested are very attractive and I would like to see them included in our project. However, there is a risk of a Strong Reference Cycle in the part of saving AnyCancellable in Activation, and I think it is also necessary to improve the fact that the user always needs to call initLayout().
> 
> So I proposal to implement LayoutProperty by "[Referencing the enclosing 'self' in a wrapper type](https://github.com/apple/swift-evolution/blob/master/proposals/0258-property-wrappers.md#referencing-the-enclosing-self-in-a-wrapper-type)" introduced as a feature of Property Wrappers
> 
> This function was also proposed when LayoutProperty was proposed, but it is not yet officially provided like @_functionBuilder. However, it is judged that all necessary feature have already been satisfied, so we suggest the use of that feature.
> 
> I referred to the following site for implementation. https://www.swiftbysundell.com/articles/accessing-a-swift-property-wrappers-enclosing-instance/

i read this posting too, But now I understand the usage. 👍

**Comment by gmlwhdtjd** [comment]
> i read this posting too, But now I understand the usage. 👍 can i ask what is risk of saving anycancellable in activation? anyway definitely this is seems better approach.

It was a rough guess that SRC might occur in the part that stores AnyCancellable through strong reference in Activation.
After reading your comment and scrutinizing it again, my suspicions were wrong, and your implementation did not cause SRC either.

**Review by gmlwhdtjd — DISMISSED** [review]
👍

**Review by gmlwhdtjd — APPROVED** [review]

**Pull request merged**
