### PR TITLE
revert appkit

### PR DESCRIPTION
**Pull request by oozoofrog**
- remove appkit supporting

### CODE REVIEW

**Comment by gmlwhdtjd** [comment]
😭 As a performance issue, appkit support should be considered again in the future.

**Comment by oozoofrog** [comment]
> 😭 As a performance issue, appkit support should be considered again in the future.

😭

**Comment by oozoofrog** [comment]
@gmlwhdtjd .... test not start. why? ....

**Comment by oozoofrog** [comment]
> @gmlwhdtjd .... test not start. why? ....

haha update GitHub action

**Comment by gmlwhdtjd** [comment]
> @gmlwhdtjd .... test not start. why? ....

it's so weird!!🤔

**Comment by oozoofrog** [comment]
> > @gmlwhdtjd .... test not start. why? ....
> 
> it's so weird!!🤔

really

**Pull request merged**
