### PR TITLE
improving testing

### PR DESCRIPTION
**Pull request by oozoofrog**
#213 

implementation test cases now has a solid, detailed and concrete structure by @gmlwhdtjd

so, we can now make more flexible api for DSL testing with layout API.

- [x] flexible and non-invasive testing constraint
- [x] testing view 
- [ ] ~flexible testing view (how possible)(someday)~

### CODE REVIEW

**Review by gmlwhdtjd — DISMISSED** [review]
LGTM 👍

**Comment by oozoofrog** [comment]
@gmlwhdtjd apply new assert function to AnchorsImplementsTests

**Review by gmlwhdtjd — COMMENTED** [review]
In my opinion, it is better to check the difference by directly comparing the values ​​rather than comparing the descriptions.

**Comment by oozoofrog** [comment]
> In my opinion, it is better to check the difference by directly comparing the values ​​rather than comparing the descriptions.

i think comparing descriptions have same result with directly compare, and can make easily readable error. are you worried about anything?

**Comment by gmlwhdtjd** [comment]
> i think comparing descriptions have same result with directly compare, and can make easily readable error. are you worried about anything?

I'm worried that if the descroption is not what I expected, there might be a problem with the test.
Also, as XCTViewAssert.swift grows, I think I need to test XCTViewAssert too.
If the XCTViewAssert is written incorrectly, there is no guarantee that the test will achieve sufficient validation.

**Comment by oozoofrog** [comment]
> > i think comparing descriptions have same result with directly compare, and can make easily readable error. are you worried about anything?
> 
> I'm worried that if the descroption is not what I expected, there might be a problem with the test. Also, as XCTViewAssert.swift grows, I think I need to test XCTViewAssert too. If the XCTViewAssert is written incorrectly, there is no guarantee that the test will achieve sufficient validation.

refactoring XCTViewAssert agreed.
about test case for XCTViewAssert can be treatable. its good idea.

i think we should believe consistency of description. otherwise we should worry about everything.

**Comment by oozoofrog** [comment]
> > i think comparing descriptions have same result with directly compare, and can make easily readable error. are you worried about anything?
> 
> I'm worried that if the descroption is not what I expected, there might be a problem with the test. Also, as XCTViewAssert.swift grows, I think I need to test XCTViewAssert too. If the XCTViewAssert is written incorrectly, there is no guarantee that the test will achieve sufficient validation.

faith of solid test case is from passing through red phase. actually we cannot believe XCTest API, and solid logic, because its user is human. so this new test function passing through red phase. its should be ok to additional test cases.

and descriptions, my opinion we should believe its consistency. in fact, we sometimes can't even believe equal function etc. in the end, the red phase that passed gives an answer, and this confident that the cases of this PR will be no problem.

**Comment by gmlwhdtjd** [comment]
@oozoofrog 
I agree with your opinion. It seems that my worries were too deep worries.

The development method of committing the red phase and turning it into a green phase looks good.
It is not a rule that must be followed, but how about set it to a recommended level?

**Review by gmlwhdtjd — APPROVED** [review]
👍

**Comment by oozoofrog** [comment]
> 

very agreed

**Pull request merged**
