### PR TITLE
Split the library into SwiftLayout and SwiftLayoutUtil

### PR DESCRIPTION
**Pull request by gmlwhdtjd**

### CODE REVIEW

**Review by oozoofrog — APPROVED** [review]
LGTM 👍

**Review by oozoofrog — DISMISSED** [review]
👍 oh my god 😹
i cleaning now, please check codes.

**Review by oozoofrog — DISMISSED** [review]
👍

**Comment by gmlwhdtjd** [comment]
Done.
Only readme edits remain

**Review by oozoofrog — APPROVED** [review]
👍

**Pull request merged**
